# Generated by Django 6.0.2 on 2026-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="contact_number",
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="exit", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
    ]
