# Generated by Django 6.0.2 on 2026-04-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_brand_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Imagename", models.CharField(max_length=100)),
                ("Image", models.ImageField(upload_to="img/")),
            ],
        ),
    ]
